pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - status-success=Travis CI - Pull Request
      - author=dependabot-preview[bot]
    actions:
      merge:
        method: rebase
      delete_head_branch: {}