language: csharp
solution: NETCore.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION_KEY
    token: 
      secure: $SONAR_TOKEN

# install:
#  - dotnet tool install --global dotnet-sonarscanner 

# before_script:
#  - export PATH="$PATH:$HOME/.dotnet/tools"

script:
#  - dotnet sonarscanner begin /k:"$SONAR_PROJECT" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" /d:sonar.language="cs" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportsPaths="lcov.opencover.xml" || true
 - dotnet build
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./lcov
#  - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN" || true
 - sonar-scanner -X


# cache:
#   directories:
#     - '$HOME/.nuget/packages'
#     - '$HOME/.local/share/NuGet/Cache'
#     - '$HOME/.sonar/cache'
