language: csharp
solution: NETCore.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2

install:
 - dotnet tool install --global dotnet-sonarscanner 

before_script:
 - export PATH="$PATH:$HOME/.dotnet/tools"

script:
 - dotnet sonarscanner begin /k:"$SONAR_PROJECT" /d:sonar.login="$SONAR_TOKEN" || true
 - dotnet restore
 - dotnet build
 - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./lcov
 - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN" || true

cache:
  directories:
    - '$HOME/.nuget/packages'
    - '$HOME/.local/share/NuGet/Cache'
    - '$HOME/.sonar/cache'
