language: csharp
solution: NETCore.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION_KEY
    token: 
      secure: $SONAR_TOKEN

script:
 - dotnet build
 - sonar-scanner
