name: Sonarcloud workflow

on:
  push:
    branches:
    - master
      
      
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Sonarscanner for dotnet
    - uses: Secbyte/dotnet-sonarscanner@v1.1
      with:
        buildCommand: dotnet build .
        testCommand: dotnet test .
        projectKey: a-project-key
        projectName: a-project-name
        sonarOrganisation: an-org
        verbose: "true"
        openCoverPaths: "tests/coverage.opencover.xml"
        coverageExclusions: "**test*.cs"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

